import { toBase64 } from './lib'

// Provider avatars: 2 terminal cells wide, one row tall (a square on screen), a square RGBA
// sprite (its frame's size, 16 or 32 pixels) filling the box. Every frame is encoded once, here.
export type Avatar = 'claude' | 'gpt'
export type Status = 'running' | 'done' | 'failed' | 'dead'
export type Picture = { rgba: string; width: number; height: number }
type Look = { run: Picture[]; done: Picture; failed: Picture }

export const SPRITE_COLS = 2
const FAILED = 0xe06c75
const EYE = 0x1a1a1a
const COLORS: Record<Avatar, number> = { claude: 0xd97757, gpt: 0xf2f2f2 }

// Sprite frames, square, N rows of N pixels: 'X' the color, 'E' eye, '.' transparent.
// CADENCE plays them in order.
const SPRITES: Record<Avatar, string[][]> = {
  // body, two eyes, arms out; the legs walk
  claude: [
    [
      '................', '................', '...XXXXXXXXXX...', '...XXXXXXXXXX...',
      '...XXEXXXXEXX...', '...XXEXXXXEXX...', '.XXXXXXXXXXXXXX.', '.XXXXXXXXXXXXXX.',
      '...XXXXXXXXXX...', '...XXXXXXXXXX...', '...XXXXXXXXXX...', '...XXXXXXXXXX...',
      '....XX....XX....', '....XX....XX....', '....XX..........', '................',
    ],
    [
      '................', '................', '...XXXXXXXXXX...', '...XXXXXXXXXX...',
      '...XXEXXXXEXX...', '...XXEXXXXEXX...', '.XXXXXXXXXXXXXX.', '.XXXXXXXXXXXXXX.',
      '...XXXXXXXXXX...', '...XXXXXXXXXX...', '...XXXXXXXXXX...', '...XXXXXXXXXX...',
      '....XX....XX....', '....XX....XX....', '..........XX....', '................',
    ],
  ],
  // the six-link knot, spun 15° a frame (it repeats every 60°); generated by
  // scripts/gpt-knot.ts, rerun it to change the shape
  gpt: [
    [
      '................................',
      '............XXX.................',
      '..........XXXXXXX...............',
      '.........XXXXXXXX...............',
      '.........XXX...XXX..XXXXXX......',
      '........XXX....XXX.XXXXXXXX.....',
      '........XXX....XXX.XXXXXXXXX....',
      '........XXX....XXX.XX....XXX....',
      '.....XX..XX..X.XXX.......XXX....',
      '...XXXXXX...XXXXXX.X.....XXX....',
      '..XXXXXXXXX.XXXXXXXXXX..XXXX....',
      '..XXX..XXXXXXX.XXXXXX..XXXX.....',
      '.XXX.....XXXXXX.XX...XXXXX......',
      '.XXX......XXXXX.XXXXXXXXX.......',
      '.XXX....XX..X.X....XXXX..XXXX...',
      '..XXX...XXX.X.....XXXXX..XXXXX..',
      '..XXXXX..XXXXX.....X.XXX...XXX..',
      '...XXXX..XXXX....X.X..XX....XXX.',
      '.......XXXXXXXXX.XXXXX......XXX.',
      '......XXXXX...XX.XXXXXX.....XXX.',
      '.....XXXX..XXXXXX.XXXXXXX..XXX..',
      '....XXXX..XXXXXXXXXX.XXXXXXXXX..',
      '....XXX.....X.XXXXXX...XXXXXX...',
      '....XXX.......XXX.X..XX..XX.....',
      '....XXX....XX.XXX....XXX........',
      '....XXXXXXXXX.XXX....XXX........',
      '.....XXXXXXXX.XXX....XXX........',
      '......XXXXXX..XXX...XXX.........',
      '...............XXXXXXXX.........',
      '...............XXXXXXX..........',
      '.................XXX............',
      '................................',
    ],
    [
      '................................',
      '.............XXXXX..............',
      '............XXXXXXXX............',
      '...........XXXXXXXXX............',
      '...........XXX....XXX...........',
      '...........XXX....XXX...........',
      '.....XXXX..XX.....XXX.XXXXX.....',
      '....XXXXXXX.X.....XXX.XXXXXX....',
      '...XXXXXXXXX..XX.XXX.XXXXXXXX...',
      '..XXXX...XXXX.XX.XXX......XXXX..',
      '..XXX.....XXXXXX.XXX.......XXX..',
      '..XXX......XXXX..XXXXX.....XXX..',
      '..XXXX...X..XXXX.XXXXXX...XXX...',
      '...XXX...XX.X.XX.XX....XXXXXX...',
      '....XXX..XX.X....X.XXXXXXXXX....',
      '.........XXXXX....XXXXXXXX......',
      '......XXXXXXXX....XXXXX.........',
      '....XXXXXXXXX.X....X.XX..XXX....',
      '...XXXXXX....XX.XX.X.XX...XXX...',
      '...XXX...XXXXXX.XXXX..X...XXXX..',
      '..XXX.....XXXXX..XXXX......XXX..',
      '..XXX.......XXX.XXXXXX.....XXX..',
      '..XXXX......XXX.XX.XXXX...XXXX..',
      '...XXXXXXXX.XXX.XX..XXXXXXXXX...',
      '....XXXXXX.XXX.....X.XXXXXXX....',
      '.....XXXXX.XXX.....XX..XXXX.....',
      '...........XXX....XXX...........',
      '...........XXX....XXX...........',
      '............XXXXXXXXX...........',
      '............XXXXXXXX............',
      '..............XXXXX.............',
      '................................',
    ],
    [
      '................................',
      '.................XXX............',
      '...............XXXXXXX..........',
      '..............XXXXXXXXX.........',
      '......XXXXX...XXX...XXX.........',
      '.....XXXXXXX..XX.....XXX........',
      '....XXXXXXXXX.XX.....XXX........',
      '....XXX...XXXX......XXX.........',
      '....XXX....XXX..XX..XXX.XXX.....',
      '....XXX.....XXXXXX.XXX.XXXXXX...',
      '....XXX...X.XXXXX.XXXX.XXXXXXX..',
      '....XXXX..XX.XXX..XXX......XXX..',
      '.....XXX.XXX.XXXXXXXXXX.....XXX.',
      '..........XX.X.X..XXXXXX....XXX.',
      '....XXXXXXXXXX...XXX.XX.....XXX.',
      '..XXXXXXXXXXXX......XXXXXXXXXX..',
      '..XXXXXXXXXX......XXXXXXXXXXXX..',
      '.XXX.....XX.XXX...XXXXXXXXXX....',
      '.XXX....XXXXXX..X.X.XX..........',
      '.XXX.....XXXXXXXXXX.XXX.XXX.....',
      '..XXX......XXX..XXX.XX..XXXX....',
      '..XXXXXXX.XXXX.XXXXX.X...XXX....',
      '...XXXXXX.XXX.XXXXXX.....XXX....',
      '.....XXX.XXX..XX..XXX....XXX....',
      '.........XXX......XXXX...XXX....',
      '........XXX.....XX.XXXXXXXXX....',
      '........XXX.....XX..XXXXXXX.....',
      '.........XXX...XXX...XXXXX......',
      '.........XXXXXXXXX..............',
      '..........XXXXXXX...............',
      '............XXX.................',
      '................................',
    ],
    [
      '................................',
      '................................',
      '.........XXX.......XXXX.........',
      '........XXXXXX....XXXXXX........',
      '.......XXXXXXXX..XXXXXXXX.......',
      '......XXXX..XXX..XXX..XXXX......',
      '......XXX....XXX.X.....XXX......',
      '......XXX....XXX.......XXX......',
      '......XXX....XXX.......XXX......',
      '......XXX...X.XXXXXX..XXX.......',
      '........X..XX.XXXXX..XXXX.......',
      '....XXXX...XX.XXX...XXXX.XXXX...',
      '..XXXXXXXXXXX.XXXXXXXXX.XXXXXX..',
      '..XXXXXXXXXXXX.XX..XXX....XXXXX.',
      '.XXX....XXXXXXX...XXXXXX....XXX.',
      '.XXX..............XX.XXX....XXX.',
      '.XXX....XXX.XX..............XXX.',
      '.XXX....XXXXXX...XXXXXXX....XXX.',
      '.XXXXX....XXX..XX.XXXXXXXXXXXX..',
      '..XXXXXX.XXXXXXXXX.XXXXXXXXXXX..',
      '...XXXX.XXXX...XXX.XX...XXXX....',
      '.......XXXX..XXXXX.XX..X........',
      '.......XXX..XXXXXX.X...XXX......',
      '......XXX.......XXX....XXX......',
      '......XXX.......XXX....XXX......',
      '......XXX.....X.XXX....XXX......',
      '......XXXX..XXX..XXX..XXXX......',
      '.......XXXXXXXX..XXXXXXXX.......',
      '........XXXXXX....XXXXXX........',
      '.........XXXX.......XXX.........',
      '................................',
      '................................',
    ],
  ],
}
const CADENCE: Record<Avatar, number[]> = { claude: [0, 1], gpt: [0, 1, 2, 3] }

function encodeSprite(sprite: string[], color: number): Picture {
  const size = sprite.length
  if (size === 0 || sprite.some(row => !new RegExp(`^[XE.]{${size}}$`).test(row))) {
    throw new Error('agent-ui: a sprite frame must be N rows of N of X, E or .')
  }
  const bytes = new Uint8Array(size * size * 4)
  for (let y = 0; y < size; y++) {
    for (let x = 0; x < size; x++) {
      const pixel = sprite[y]?.[x]
      const rgb = pixel === 'X' ? color : pixel === 'E' ? EYE : null
      if (rgb !== null) bytes.set([(rgb >> 16) & 255, (rgb >> 8) & 255, rgb & 255, 255], (y * size + x) * 4)
    }
  }
  return { rgba: toBase64(bytes), width: size, height: size }
}

function encodePicture(avatar: Avatar, step: number, color: number): Picture {
  const sprite = SPRITES[avatar][CADENCE[avatar][step] ?? -1]
  if (!sprite) throw new Error(`agent-ui: ${avatar} has no sprite frame at step ${step}`)
  return encodeSprite(sprite, color)
}

export const dim = (rgb: number) => ((((rgb >> 16) & 255) * 0.4) << 16) | ((((rgb >> 8) & 255) * 0.4) << 8) | ((rgb & 255) * 0.4)

// Done and failed show step 0.
const PICTURES = Object.fromEntries(
  (Object.keys(SPRITES) as Avatar[]).map(avatar => {
    const color = COLORS[avatar]
    return [avatar, {
      run: CADENCE[avatar].map((_, step) => encodePicture(avatar, step, color)),
      done: encodePicture(avatar, 0, dim(color)),
      failed: encodePicture(avatar, 0, FAILED),
    }]
  }),
) as Record<Avatar, Look>

export function avatarPicture(avatar: Avatar, status: Status, tick: number): Picture {
  const look = PICTURES[avatar]
  if (status === 'running') return look.run[tick % look.run.length] as Picture
  return status === 'done' ? look.done : look.failed
}

export function avatarOf(kind: string): Avatar | null {
  return kind === 'gpt' ? kind : kind === 'claude' || kind === 'claude-panel' ? 'claude' : null
}
