import { toBase64 } from './lib'

// Provider avatars: 2 terminal cells wide, one row tall (a square on screen). Where the
// terminal draws pictures, a square RGBA sprite (its frame's size, 16 or 32 pixels) fills
// the box; elsewhere braille (2x4 dots a cell, so 4x4 pixels) in a Raster, and the same
// braille is the picture's alt text. Every frame is encoded once, here.
export type Avatar = 'claude' | 'gpt' | 'kimi'
export type Status = 'running' | 'done' | 'failed' | 'dead'
export type Picture = { source: { rgba: string; width: number; height: number }; alt: string }
type Look<T> = { run: T[]; done: T; failed: T }

export const SPRITE_COLS = 2
const DEFAULT_BG = 0x01000000
const FAILED = 0xe06c75
const WHITE = 0xf2f2f2
const EYE = 0x1a1a1a
const COLORS: Record<Avatar, { main: number; accent: number }> = {
  claude: { main: 0xd97757, accent: 0xd97757 },
  gpt: { main: WHITE, accent: WHITE },
  kimi: { main: WHITE, accent: 0x5b7fff },
}
const DOT_BITS = [
  [0x01, 0x02, 0x04, 0x40],
  [0x08, 0x10, 0x20, 0x80],
]

// Braille frames, 4 rows of 4 pixels. 'X' is the main color, 'B' the accent. Color is per
// cell, so the Kimi dot (upper right, in the right cell) turns that whole cell blue: the
// K's right half and the dot. A cadence plays the frames in order.
const FRAMES: Record<Avatar, string[][]> = {
  // eyes are the gaps; the legs alternate
  claude: [
    ['XXXX', 'X..X', 'XXXX', 'X..X'],
    ['XXXX', 'X..X', 'XXXX', '.XX.'],
  ],
  // a ring with a center gap, turning
  gpt: [
    ['.XX.', 'X..X', 'X..X', '.XX.'],
    ['XXX.', 'X..X', 'X..X', '.XXX'],
    ['.XXX', 'X..X', 'X..X', 'XXX.'],
  ],
  // the K flips left to right, its dot stays
  kimi: [
    ['X.XB', 'XX..', 'XX..', 'X.X.'],
    ['X.XB', '.XX.', '.XX.', 'X.X.'],
  ],
}

// Sprite frames, square, N rows of N pixels: 'X' main, 'B' accent, 'E' eye, '.' transparent.
// SPRITE_CADENCE plays them; its step k shows the braille frame at CADENCE step k as alt.
const SPRITES: Record<Avatar, string[][]> = {
  // body, two eyes, arms out; the legs walk
  claude: [
    [
      '................', '................', '...XXXXXXXXXX...', '...XXXXXXXXXX...',
      '...XXEXXXXEXX...', '...XXEXXXXEXX...', '.XXXXXXXXXXXXXX.', '.XXXXXXXXXXXXXX.',
      '...XXXXXXXXXX...', '...XXXXXXXXXX...', '...XXXXXXXXXX...', '...XXXXXXXXXX...',
      '....XX....XX....', '....XX....XX....', '....XX..........', '................',
    ],
    [
      '................', '................', '...XXXXXXXXXX...', '...XXXXXXXXXX...',
      '...XXEXXXXEXX...', '...XXEXXXXEXX...', '.XXXXXXXXXXXXXX.', '.XXXXXXXXXXXXXX.',
      '...XXXXXXXXXX...', '...XXXXXXXXXX...', '...XXXXXXXXXX...', '...XXXXXXXXXX...',
      '....XX....XX....', '....XX....XX....', '..........XX....', '................',
    ],
  ],
  // the six-link knot, spun 15° a frame (it repeats every 60°); generated by
  // scripts/gpt-knot.ts, rerun it to change the shape
  gpt: [
    [
      '................................',
      '............XXX.................',
      '..........XXXXXXX...............',
      '.........XXXXXXXX...............',
      '.........XXX...XXX..XXXXXX......',
      '........XXX....XXX.XXXXXXXX.....',
      '........XXX....XXX.XXXXXXXXX....',
      '........XXX....XXX.XX....XXX....',
      '.....XX..XX..X.XXX.......XXX....',
      '...XXXXXX...XXXXXX.X.....XXX....',
      '..XXXXXXXXX.XXXXXXXXXX..XXXX....',
      '..XXX..XXXXXXX.XXXXXX..XXXX.....',
      '.XXX.....XXXXXX.XX...XXXXX......',
      '.XXX......XXXXX.XXXXXXXXX.......',
      '.XXX....XX..X.X....XXXX..XXXX...',
      '..XXX...XXX.X.....XXXXX..XXXXX..',
      '..XXXXX..XXXXX.....X.XXX...XXX..',
      '...XXXX..XXXX....X.X..XX....XXX.',
      '.......XXXXXXXXX.XXXXX......XXX.',
      '......XXXXX...XX.XXXXXX.....XXX.',
      '.....XXXX..XXXXXX.XXXXXXX..XXX..',
      '....XXXX..XXXXXXXXXX.XXXXXXXXX..',
      '....XXX.....X.XXXXXX...XXXXXX...',
      '....XXX.......XXX.X..XX..XX.....',
      '....XXX....XX.XXX....XXX........',
      '....XXXXXXXXX.XXX....XXX........',
      '.....XXXXXXXX.XXX....XXX........',
      '......XXXXXX..XXX...XXX.........',
      '...............XXXXXXXX.........',
      '...............XXXXXXX..........',
      '.................XXX............',
      '................................',
    ],
    [
      '................................',
      '.............XXXXX..............',
      '............XXXXXXXX............',
      '...........XXXXXXXXX............',
      '...........XXX....XXX...........',
      '...........XXX....XXX...........',
      '.....XXXX..XX.....XXX.XXXXX.....',
      '....XXXXXXX.X.....XXX.XXXXXX....',
      '...XXXXXXXXX..XX.XXX.XXXXXXXX...',
      '..XXXX...XXXX.XX.XXX......XXXX..',
      '..XXX.....XXXXXX.XXX.......XXX..',
      '..XXX......XXXX..XXXXX.....XXX..',
      '..XXXX...X..XXXX.XXXXXX...XXX...',
      '...XXX...XX.X.XX.XX....XXXXXX...',
      '....XXX..XX.X....X.XXXXXXXXX....',
      '.........XXXXX....XXXXXXXX......',
      '......XXXXXXXX....XXXXX.........',
      '....XXXXXXXXX.X....X.XX..XXX....',
      '...XXXXXX....XX.XX.X.XX...XXX...',
      '...XXX...XXXXXX.XXXX..X...XXXX..',
      '..XXX.....XXXXX..XXXX......XXX..',
      '..XXX.......XXX.XXXXXX.....XXX..',
      '..XXXX......XXX.XX.XXXX...XXXX..',
      '...XXXXXXXX.XXX.XX..XXXXXXXXX...',
      '....XXXXXX.XXX.....X.XXXXXXX....',
      '.....XXXXX.XXX.....XX..XXXX.....',
      '...........XXX....XXX...........',
      '...........XXX....XXX...........',
      '............XXXXXXXXX...........',
      '............XXXXXXXX............',
      '..............XXXXX.............',
      '................................',
    ],
    [
      '................................',
      '.................XXX............',
      '...............XXXXXXX..........',
      '..............XXXXXXXXX.........',
      '......XXXXX...XXX...XXX.........',
      '.....XXXXXXX..XX.....XXX........',
      '....XXXXXXXXX.XX.....XXX........',
      '....XXX...XXXX......XXX.........',
      '....XXX....XXX..XX..XXX.XXX.....',
      '....XXX.....XXXXXX.XXX.XXXXXX...',
      '....XXX...X.XXXXX.XXXX.XXXXXXX..',
      '....XXXX..XX.XXX..XXX......XXX..',
      '.....XXX.XXX.XXXXXXXXXX.....XXX.',
      '..........XX.X.X..XXXXXX....XXX.',
      '....XXXXXXXXXX...XXX.XX.....XXX.',
      '..XXXXXXXXXXXX......XXXXXXXXXX..',
      '..XXXXXXXXXX......XXXXXXXXXXXX..',
      '.XXX.....XX.XXX...XXXXXXXXXX....',
      '.XXX....XXXXXX..X.X.XX..........',
      '.XXX.....XXXXXXXXXX.XXX.XXX.....',
      '..XXX......XXX..XXX.XX..XXXX....',
      '..XXXXXXX.XXXX.XXXXX.X...XXX....',
      '...XXXXXX.XXX.XXXXXX.....XXX....',
      '.....XXX.XXX..XX..XXX....XXX....',
      '.........XXX......XXXX...XXX....',
      '........XXX.....XX.XXXXXXXXX....',
      '........XXX.....XX..XXXXXXX.....',
      '.........XXX...XXX...XXXXX......',
      '.........XXXXXXXXX..............',
      '..........XXXXXXX...............',
      '............XXX.................',
      '................................',
    ],
    [
      '................................',
      '................................',
      '.........XXX.......XXXX.........',
      '........XXXXXX....XXXXXX........',
      '.......XXXXXXXX..XXXXXXXX.......',
      '......XXXX..XXX..XXX..XXXX......',
      '......XXX....XXX.X.....XXX......',
      '......XXX....XXX.......XXX......',
      '......XXX....XXX.......XXX......',
      '......XXX...X.XXXXXX..XXX.......',
      '........X..XX.XXXXX..XXXX.......',
      '....XXXX...XX.XXX...XXXX.XXXX...',
      '..XXXXXXXXXXX.XXXXXXXXX.XXXXXX..',
      '..XXXXXXXXXXXX.XX..XXX....XXXXX.',
      '.XXX....XXXXXXX...XXXXXX....XXX.',
      '.XXX..............XX.XXX....XXX.',
      '.XXX....XXX.XX..............XXX.',
      '.XXX....XXXXXX...XXXXXXX....XXX.',
      '.XXXXX....XXX..XX.XXXXXXXXXXXX..',
      '..XXXXXX.XXXXXXXXX.XXXXXXXXXXX..',
      '...XXXX.XXXX...XXX.XX...XXXX....',
      '.......XXXX..XXXXX.XX..X........',
      '.......XXX..XXXXXX.X...XXX......',
      '......XXX.......XXX....XXX......',
      '......XXX.......XXX....XXX......',
      '......XXX.....X.XXX....XXX......',
      '......XXXX..XXX..XXX..XXXX......',
      '.......XXXXXXXX..XXXXXXXX.......',
      '........XXXXXX....XXXXXX........',
      '.........XXXX.......XXX.........',
      '................................',
      '................................',
    ],
  ],
  // the K, then the K half turned; the dot stays
  kimi: [
    [
      '................', '................', '..XX......XX.BB.', '..XX.....XX..BB.',
      '..XX....XX......', '..XX...XX.......', '..XX..XX........', '..XXXXX.........',
      '..XXXXX.........', '..XX..XX........', '..XX...XX.......', '..XX....XX......',
      '..XX.....XX.....', '..XX......XX....', '................', '................',
    ],
    [
      '................', '................', '....XX...XX..BB.', '....XX..XX...BB.',
      '....XX..XX......', '....XX.XX.......', '....XX.XX.......', '....XXXX........',
      '....XXXX........', '....XX.XX.......', '....XX.XX.......', '....XX..XX......',
      '....XX..XX......', '....XX...XX.....', '................', '................',
    ],
  ],
}
const CADENCE: Record<Avatar, number[]> = { claude: [0, 1], gpt: [0, 1, 0, 2], kimi: [0, 0, 1, 1] }
const SPRITE_CADENCE: Record<Avatar, number[]> = { claude: [0, 1], gpt: [0, 1, 2, 3], kimi: [0, 0, 1, 1] }


// One braille code point a cell, with the cell's color.
function brailleCells(frame: string[], main: number, accent: number): { glyph: number; color: number }[] {
  return Array.from({ length: SPRITE_COLS }, (_, cell) => {
    let bits = 0
    let hasAccent = false
    for (let dx = 0; dx < 2; dx++) {
      for (let dy = 0; dy < 4; dy++) {
        const pixel = frame[dy]?.[cell * 2 + dx]
        if (pixel === 'X' || pixel === 'B') bits |= DOT_BITS[dx]?.[dy] ?? 0
        if (pixel === 'B') hasAccent = true
      }
    }
    return { glyph: bits ? 0x2800 + bits : 0x20, color: hasAccent ? accent : main }
  })
}

function encodeCells(frame: string[], main: number, accent: number): string {
  const words = Uint32Array.from(brailleCells(frame, main, accent).flatMap(({ glyph, color }) => [glyph, color, DEFAULT_BG]))
  return toBase64(new Uint8Array(words.buffer))
}

function encodeSprite(sprite: string[], main: number, accent: number): Picture['source'] {
  const size = sprite.length
  if (size === 0 || sprite.some(row => !new RegExp(`^[XBE.]{${size}}$`).test(row))) {
    throw new Error('agent-ui: a sprite frame must be N rows of N of X, B, E or .')
  }
  const bytes = new Uint8Array(size * size * 4)
  for (let y = 0; y < size; y++) {
    for (let x = 0; x < size; x++) {
      const pixel = sprite[y]?.[x]
      const rgb = pixel === 'X' ? main : pixel === 'B' ? accent : pixel === 'E' ? EYE : null
      if (rgb !== null) bytes.set([(rgb >> 16) & 255, (rgb >> 8) & 255, rgb & 255, 255], (y * size + x) * 4)
    }
  }
  return { rgba: toBase64(bytes), width: size, height: size }
}

function brailleAt(avatar: Avatar, step: number): string[] {
  const frame = FRAMES[avatar][CADENCE[avatar][step] ?? -1]
  if (!frame) throw new Error(`agent-ui: ${avatar} has no braille frame at step ${step}`)
  return frame
}

function encodePicture(avatar: Avatar, step: number, main: number, accent: number): Picture {
  const sprite = SPRITES[avatar][SPRITE_CADENCE[avatar][step] ?? -1]
  if (!sprite) throw new Error(`agent-ui: ${avatar} has no sprite frame at step ${step}`)
  const alt = brailleCells(brailleAt(avatar, step), main, accent).map(({ glyph }) => String.fromCodePoint(glyph)).join('')
  return { source: encodeSprite(sprite, main, accent), alt }
}

export const dim = (rgb: number) => ((((rgb >> 16) & 255) * 0.4) << 16) | ((((rgb >> 8) & 255) * 0.4) << 8) | ((rgb & 255) * 0.4)

// `encode` takes a cadence step; done and failed show step 0.
function looks<T>(encode: (avatar: Avatar, step: number, main: number, accent: number) => T): Record<Avatar, Look<T>> {
  return Object.fromEntries(
    (Object.keys(FRAMES) as Avatar[]).map(avatar => {
      if (SPRITE_CADENCE[avatar].length !== CADENCE[avatar].length) throw new Error(`agent-ui: ${avatar} cadences differ in length`)
      const { main, accent } = COLORS[avatar]
      return [avatar, {
        run: CADENCE[avatar].map((_, step) => encode(avatar, step, main, accent)),
        done: encode(avatar, 0, dim(main), dim(accent)),
        failed: encode(avatar, 0, FAILED, FAILED),
      }]
    }),
  ) as Record<Avatar, Look<T>>
}

const CELLS = looks((avatar, step, main, accent) => encodeCells(brailleAt(avatar, step), main, accent))
const PICTURES = looks(encodePicture)

function pick<T>(look: Look<T>, status: Status, tick: number): T {
  if (status === 'running') return look.run[tick % look.run.length] as T
  return status === 'done' ? look.done : look.failed
}

export const avatarCells = (avatar: Avatar, status: Status, tick: number): string => pick(CELLS[avatar], status, tick)
export const avatarPicture = (avatar: Avatar, status: Status, tick: number): Picture => pick(PICTURES[avatar], status, tick)

export function avatarOf(kind: string): Avatar | null {
  return kind === 'gpt' || kind === 'kimi' ? kind : kind === 'claude' || kind === 'claude-panel' ? 'claude' : null
}
